title: Find a needle in haystack
description: Distributed-System | Java | Golang | Infrastructure | Operating System
baseurl: "" # the subpath of your site, e.g. /blog
url: "kkzhang-tt.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    KKZHANG
author-image:   1.jpg
author-job:     Software Engineer
author-email:   kkzhang1029@gmail.com # Add your email for contant form.
author-twitter: KZ25674171 # Add your twitter account
about-author:   👋 Hi, I’m @kkzhang.<br/> 👍I am now working at @MeiTuan, engaged in middleware development.<br> ✌️ I used to work at @ByteDance, develop software about Instant Messaging. <br> ☎️ I am interested in distributed-system & operating-system.<br> 🧭 The main development language is java, and I also know little golang. 

# Social settings
social-twitter:   KZ25674171
social-facebook:
social-github:    kkzhang-tt
social-pinterest: 
social-instagram: kzhang29
social-youtube:
social-vk:   
social-linkedin: k-z-23575b202

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
